# Generated by Django 4.2.2 on 2023-06-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='http_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
