# Generated by Django 4.2.2 on 2023-06-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_personx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persony',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
    ]
